import Meeting from "./components/root/home/meetings.tsx";
import NavBar from "./components/pages/NavBar.tsx";
import Footer from "./components/pages/Footer.tsx";
import HomeLayout from "./components/root/home/layout.tsx";
import Home from "./components/pages/Home.tsx";
import Upcoming from "./components/pages/Upcoming.tsx";
import Previous from "./components/pages/Previous.tsx";
import Recordings from "./components/pages/Recordings.tsx";
import PersonalRoom from "./components/pages/PersonalRoom.tsx";
import SignUp from "./components/auth/SignUp.tsx";
import AuthButtons from "./components/auth/SignUp.tsx";
import SignUps from "./components/auth/SignIn.tsx";
export {Meeting, NavBar, Footer, HomeLayout, Home, Upcoming, AuthButtons, SignUps, Previous, Recordings,PersonalRoom, SignUp};